BUTTONS_CONFIG = [
    {
        "id": "start",
        "screen": "menu",
        "x_pct": 0.75,
        "y_pct": 0.50,
        "w": 200,
        "h": 50,
        "text": "开始游戏",
        "bg_color": [30, 144, 255],
        "fg_color": [255, 255, 255],
        "font_size": 28,
        "font_name": "Microsoft YaHei",
        "callback": "on_start",
    },
    {
        "id": "settings",
        "screen": "menu",
        "x_pct": 0.75,
        "y_pct": 0.60,
        "w": 200,
        "h": 50,
        "text": "设置",
        "bg_color": [100,100,100],
        "fg_color": [255,255,255],
        "font_size": 24,
        "font_name": "Microsoft YaHei",
        "callback": "on_settings",
    },
    {
        "id": "quit",
        "screen": "menu",
        "x_pct": 0.75,
        "y_pct": 0.70,
        "w": 200,
        "h": 50,
        "text": "退出",
        "bg_color": [200, 50, 50],
        "fg_color": [255,255,255],
        "font_size": 24,
        "font_name": "Microsoft YaHei",
        "callback": "on_quit",
    }
]

# 额外界面按钮配置：play 和 settings
BUTTONS_CONFIG += [
    {
        "id": "play_back",
        "screen": "play",
        "anchor": "topright",
        "dx": -100,
        "dy": 16,
        "w": 100,
        "h": 32,
        "text": "返回菜单",
        "bg_color": [100, 100, 100],
        "fg_color": [255, 255, 255],
        "font_size": 20,
        "font_name": "Microsoft YaHei",
        "callback": "on_back",
    },
    {
        "id": "play_send",
        "screen": "play",
        "anchor": "bottomright",
        "dx": -16,
        "dy": -16,
        "w": 90,
        "h": 40,
        "text": "发送",
        "bg_color": [60, 140, 250],
        "fg_color": [255, 255, 255],
        "font_size": 20,
        "font_name": "Microsoft YaHei",
        "callback": "on_send",
    },
    {
        "id": "settings_back",
        "screen": "settings",
        "x_pct": 0.04,
        "y_pct": 0.05,
        "w_pct": 0.14,
        "h": 40,
        "text": "← 返回菜单",
        "bg_color": [100, 100, 100],
        "fg_color": [255, 255, 255],
        "font_size": 20,
        "font_name": "Microsoft YaHei",
        "callback": "on_back",
    },
    {
        "id": "settings_light",
        "screen": "settings",
        "x_pct": 0.22,
        "y_pct": 0.46,
        "w_pct": 0.14,
        "h": 36,
        "text": "浅色主题",
        "bg_color": [180, 200, 220],
        "fg_color": [255, 255, 255],
        "font_size": 18,
        "font_name": "Microsoft YaHei",
        "callback": "on_light_theme",
    },
    {
        "id": "settings_dark",
        "screen": "settings",
        "x_pct": 0.38,
        "y_pct": 0.46,
        "w_pct": 0.14,
        "h": 36,
        "text": "深色主题",
        "bg_color": [80, 90, 110],
        "fg_color": [255, 255, 255],
        "font_size": 18,
        "font_name": "Microsoft YaHei",
        "callback": "on_dark_theme",
    },
    {
        "id": "settings_fullscreen",
        "screen": "settings",
        "x_pct": 0.54,
        "y_pct": 0.46,
        "w_pct": 0.14,
        "h": 36,
        "text": "全屏: 否",
        "bg_color": [120, 200, 120],
        "fg_color": [255, 255, 255],
        "font_size": 18,
        "font_name": "Microsoft YaHei",
        "callback": "on_fullscreen",
    },
]
